@startuml LayerStructure_CommandFlow

participant Controller
participant UseCase
participant DomainObject
participant Repository
database DB

Controller -> Controller: パラメータ DTO 生成
Controller -> UseCase: 登録/更新処理実行(DTO)
UseCase -> Repository: 集約を取得(Id)
Repository -> DB: SQLを発行（select）
DB -> Repository: ORM で受け取る
Repository -> Repository: ORM を集約に変換
Repository -> UseCase: 集約ルートを返却
UseCase -> DomainObject: 集約の状態変更()
DomainObject -> DomainObject: 整合性を保つための検証
DomainObject -> DomainObject: 内部状態変更
DomainObject -> UseCase
UseCase -> Repository: 集約を永続化(集約ルート)
Repository -> Repository: 集約を ORM に変換
Repository -> DB: SQL を発行（insert/update/delete）
DB -> Repository
Repository -> UseCase
UseCase -> Controller

@enduml
