@startuml LayerStructure_CommandFlow

participant Controller
participant UseCase
participant DomainObject
participant Repository
database DB

Controller -> Controller: パラメータ DTO 生成
Controller -> UseCase: 登録/更新処理実行(DTO)
UseCase -> Repository: DomainObject を取得(Id)
Repository -> DB: SQLを発行（select）
DB -> Repository: ORM で受け取る
Repository -> Repository: ORM を DomainObject に変換
Repository -> UseCase: DomainObject を返却
UseCase -> DomainObject: DomainObject の状態変更()
DomainObject -> DomainObject: バリデーション
DomainObject -> DomainObject: 内部状態変更
DomainObject -> UseCase
UseCase -> Repository: DomainObject を永続化(DomainObject)
Repository -> Repository: DomainObject を ORM に変換
Repository -> DB: SQL を発行（insert/update/delete）
DB -> Repository
Repository -> UseCase
UseCase -> Controller

@enduml
